version: 2.1
jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm run test

  release:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12
    steps:
      - run:
          name: Compile To Javascript For Release
          command: npm run build
      - run:
          name: Push New Release To NPM and Tag in Git
          command: npx semantic-release


workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only:
                - master

