version: 2.1
jobs:
  build_docker:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm run test

  deploy:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Compile To Javascript For Release
          command: npm run build
      - run:
          name: Authenticate with NPM
          command: |
            echo '//registry.npmjs.org/:_authToken=$NPM_CONFIG_TOKEN' >> .npmrc
            npm login
      - run:
          name: Push New Release To NPM 
          command: npm publish


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_docker
      - deploy:
          requires:
            - build_docker
          filters:
            branches:
              only:
                - release

